services:

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:80"
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8000:80"
    volumes:
      - ./src-api:/app
  