FROM python:3.12-slim

WORKDIR /app

COPY ./src-api/requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

EXPOSE 80

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload", "--reload-dir", "/app"]