services:

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./ui-compiled:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/default.conf
  api:
    image: python:3.11
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8000:80"
    volumes:
      - ./src-api:/app
  