services:

  web:
    depends_on:
      - api
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:80"
      
  api:
    depends_on:
      db:
        condition: service_healthy # Ensure that postgres is not only running but has finished initializing
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/mydatabase
    volumes:
      - ./src-api:/app

  db: 
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  db_data:
  